apiVersion: apps/v1
kind: Deployment
metadata:
  name: testinga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testinga
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: testinga
    spec:
      containers:
      - image: nginx    #若使用“开源镜像中心”的镜像，可直接填写镜像名称；若使用“我的镜像”中的镜像，请在SWR中获取具体镜像地址。
        imagePullPolicy: IfNotPresent
        name: nginx
      imagePullSecrets:
      - name: default-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: testinga
  name: testinga
spec:
  ports:
  - name: service0
    port: 80                 # 访问Service的端口
    protocol: TCP           # 访问Service的协议，支持TCP和UDP
    targetPort: 80           # Service访问目标容器的端口，本例中nginx镜像默认使用80端口
  selector:                  # 标签选择器，Service通过标签选择Pod，将访问Service的流量转发给Pod
    app: testinga
  type: ClusterIP            # Service的类型，ClusterIP表示在集群内访问
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testinga
  namespace: default
spec:
  ingressClassName: myingress3
  rules:
    - host: testinga.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: testinga
                port:
                  number: 80
            path: /
  # This section is only required if TLS is to be enabled for the Ingress
#  tls:
#    - hosts:
#      - ingressbbb.com
#      secretName: example-tls
