
controller:
  hostNetwork: true #使用主机网络
  replicaCount: 1 # 多副本
  image:   #controller镜像地址
    repository: anjia0532/google-containers.ingress-nginx.controller   #请根据集群所在区域进行替换
    registry: ""
    image: ""
    tag: "v1.1.1"
    digest: ""
  ingressClassResource:
    name: myingress3
    controllerValue: "k8s.io/ingress-nginx-myingress3"
  ingressClass: myingress3
  service: 
    annotations: {
    kubernetes.io/elb.id: 7e7bd3ea-c6c1-4741-91e5-7561643e50b7     #ELB ID
    }
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443
      tcp:
        8080: 32808
  config: {
    "keep-alive-requests": "100"
  }
  electionID: myingress3
  admissionWebhooks:
    patch:
      image:
        repository: anjia0532/google-containers.ingress-nginx.kube-webhook-certgen    #该地址为国外镜像源，可能正常无法拉取，请自行替换。
        tag: v1.1.1
        digest: ""
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
defaultBackend: 
  image:   #defaultBackend镜像地址
    repository: anjia0532/defaultbackend      #请根据集群所在区域进行替换
    tag: "1.1"
    digest: ""
imagePullSecrets:
  - name: default-secret


